/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Arrest;
import java.awt.BorderLayout;
import java.awt.Button;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Panel;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSplitPane;

/**
 *
 * @author Cécile
 */
public class DetailsView extends javax.swing.JPanel {

    /**
     * Creates new form DetailsView
     */
    JPanel imgContainer = new JPanel();
    JPanel centerDetails = new JPanel();
    JPanel rightDetails = new JPanel();
    
    Arrest arrest = new Arrest();
    
    public DetailsView() {
        initComponents();

        setLayout (new BorderLayout());
        
        Button next = new Button ("Next >>");
        Button back = new Button ("<< Back");
        add(next, BorderLayout.LINE_END);
        add(back, BorderLayout.LINE_START);
        this.setBorder(BorderFactory.createLineBorder(Color.black));
        
        JPanel detailsContainer = new JPanel();
        detailsContainer.setPreferredSize(new Dimension(1000, 200));
        add(detailsContainer, BorderLayout.CENTER);
        
        imgContainer.setPreferredSize(new Dimension(200, 190));
        imgContainer.setBorder(BorderFactory.createLineBorder(Color.black));
        detailsContainer.add(imgContainer, BorderLayout.LINE_START);
          
        centerDetails.setPreferredSize(new Dimension(400, 190));
        centerDetails.setBorder(BorderFactory.createLineBorder(Color.black));
        detailsContainer.add(centerDetails, BorderLayout.CENTER);
        
        rightDetails.setPreferredSize(new Dimension(400, 190));
        rightDetails.setBorder(BorderFactory.createLineBorder(Color.black));
        detailsContainer.add(rightDetails, BorderLayout.LINE_END);
        
        setInfo();
    }
    
    public void setInfo(){
        JLabel nom = new JLabel();
        nom.setText("Nom :");
        centerDetails.add(nom);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
