package View;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.Box;

public class MainView extends javax.swing.JFrame {
    
    private Box rightBox;

    public MainView() {
        setLayout (new BorderLayout());
        this.setTitle("Baltimore Database Manager");
        this.setLocationRelativeTo(null);
        this.setSize(1200,1000);
        rightBox =  Box.createVerticalBox();
        rightBox.setBorder(BorderFactory.createLineBorder(Color.black));
//        FlowLayout layout = new FlowLayout();
//        rightBox.setLayout(layout);
        this.add(rightBox, BorderLayout.LINE_END);
        
    }
    
     public Box getRightBox() {
        return rightBox;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}