/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import baltimore.ListCtrl;
import baltimore.MainCtrl;
import java.awt.BorderLayout;

/**
 *
 * @author Coline
 */
public class MainView extends javax.swing.JDialog {

    /**
     * Creates new form MainView
     */
    public MainView() {

        initComponents();
        setLayout (new BorderLayout());
        this.setSize(1200,1024);
        this.setTitle("Baltimore Database Manager");
        this.setLocationRelativeTo(null);
        
        MainCtrl mainCtrl= new MainCtrl();
        //ChartCtrl cc = new ChartCtrl(mainCtrl.getArrestList(),this);
        ListCtrl lc = new ListCtrl();
        
        javax.swing.JList jason = new javax.swing.JList();
        //ListView List = new ListView(jason);
        //List.setPreferredSize(new Dimension(300, 700));
        
        this.add(lc.List,BorderLayout.LINE_END);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
